# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0003_auto_20160211_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtemplate',
            name='ref',
            field=models.CharField(choices=[('SIGN', "Cr\xe9ation d'un compte"), ('MAIL', "Confirmation d'adresse e-mail"), (3, 'Order Credit card')], max_length=4, verbose_name='Gabarit'),
        ),
    ]
