# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('slug', models.SlugField(default=None, editable=False, unique=True, verbose_name='Adresse')),
                ('order', models.IntegerField(verbose_name="Ordre d'apparition")),
                ('description', models.TextField(help_text='Description (pour r\xe9f\xe9rencement)', verbose_name='Meta description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cr\xe9ation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mise \xe0 jour')),
            ],
            options={
                'ordering': ['order'],
                'verbose_name': "Categorie d'une actuali\xe9",
                'verbose_name_plural': 'Categories des actualit\xe9s',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90, unique=True, verbose_name='Titre')),
                ('subtitle', models.CharField(max_length=150, verbose_name='Titre second niveau')),
                ('slug', models.SlugField(default=None, editable=False, unique=True, verbose_name='Adresse')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('description', models.TextField(help_text='Description (pour r\xe9f\xe9rencement)', verbose_name='Meta description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cr\xe9ation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mise \xe0 jour')),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Publication')),
                ('state', models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Published')], verbose_name='Publication')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.Category')),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover', to='images.Image', verbose_name='Image Vignette')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='images.Image', verbose_name='Image Article')),
                ('related_articles', models.ManyToManyField(blank=True, related_name='referenced_articles', to='blog.Post', verbose_name='Artciles associ\xe9s')),
            ],
            options={
                'ordering': ['-published_at'],
                'verbose_name': 'Actuali\xe9',
                'verbose_name_plural': 'Actualit\xe9s',
            },
        ),
    ]
