# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_content',
            field=models.TextField(default='', verbose_name='R\xe9sum\xe9'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Publication'),
        ),
    ]
